---
ID: "efed1c6e-e8e8-4e2d-8ae8-166f05a06469"
Parent: "60660225-7fd1-4303-bbca-df2fde1ec113"
Template: "60660225-7fd1-4303-bbca-df2fde1ec113"
Path: /sitecore/templates/Foundation/SocialServices/DataSource/Facebook Settings/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180303T100238Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
