---
ID: "36c0d188-2a28-4c04-a6b9-ac283630d421"
Parent: "91a6c2aa-f068-4e3c-923d-c8378fdb9b38"
Template: "91a6c2aa-f068-4e3c-923d-c8378fdb9b38"
Path: /sitecore/templates/Foundation/SocialServices/DataSource/Twitter Settings/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180303T100245Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
